---
- name: Create owner account
  sudo: yes
  user:
    state: present
    name: "{{ owner_name }}"
    comment: "{{ owner_comment }}"
    append: yes
    groups: wheel
  tags:
    - redhat
- name: Set wheel group as sudoers
  sudo: yes
  template:
    src: owner.j2
    dest: /etc/sudoers.d/{{ owner_name }}
    validate: "visudo -cf %s"
- name: Set password for owner
  sudo: yes
  shell: echo "{{ owner_name }}:{{ owner_password }}" | chpasswd --crypt-method=SHA512
  changed_when: false
- name: Verify existant of ssh-key
  delegate_to: 127.0.0.1
  shell: test -f {{ inventory_hostname }}_{{ owner_name }}_rsa.pub
  register: verify_sshkey
  failed_when: false
  changed_when: verify_sshkey.rc != 0
- name: Generate ssh key in local
  when: verify_sshkey | changed
  delegate_to: 127.0.0.1
  command: ssh-keygen -b 2048 -t rsa -P "" -f {{ inventory_hostname }}_{{ owner_name }}_rsa
- name: Upload authorized_key
  sudo: yes
  sudo_user: "{{ owner_name }}"
  authorized_key:
    state: present
    user: "{{ owner_name }}"
    key: "{{ item }}"
  with_file:
    - "{{ inventory_hostname }}_{{ owner_name }}_rsa.pub"
