---
- name: Create owner account
  sudo: yes
  user:
    state: present
    name: "{{ owner_name }}"
    comment: "{{ owner_comment }}"
    append: yes
    groups: wheel
  tags:
    - redhat
- name: Set wheel group as sudoers
  sudo: yes
  template:
    src: owner.j2
    dest: /etc/sudoers.d/{{ owner_name }}
    validate: "visudo -cf %s"
- name: Set password for owner
  sudo: yes
  shell: echo "{{ owner_name }}:{{ owner_password }}" | chpasswd --crypt-method=SHA512
  changed_when: false
